name: CI for DevOps Monitoring App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Kód letöltése
      uses: actions/checkout@v3

    - name: Python beállítása
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: psutil telepítése
      run: pip install psutil

    - name: Script futtatása
      run: python monitor.py
