name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Kód letöltése
      uses: actions/checkout@v3

    - name: DockerHub-ba belépés
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Docker image build
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-monitor:latest .

    - name: Docker image push
      run: docker push ${{ secrets.DOCKER_USERNAME }}/devops-monitor:latest
