name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Kód letöltése
        uses: actions/checkout@v3

      - name: Python beállítása
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Követelmények telepítése
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Tesztek futtatása
        run: pytest

  docker-build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Kód letöltése
        uses: actions/checkout@v3

      - name: Docker image build
        run: |
          docker build -t mymonitorapp .
