name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Kód letöltése
        uses: actions/checkout@v3

      - name: Python beállítása
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Követelmények telepítése
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Tesztek futtatása
        run: pytest

  docker-build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Kód letöltése
        uses: actions/checkout@v3

      - name: Bejelentkezés DockerHub-ra
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Docker image build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-monitoring:latest .

      - name: Docker image push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/devops-monitoring:latest
